### ISSUE TITLE
ImportError: /usr/lib64/libm.so.6: version `GLIBC_2.27' not found (required by /mnt/dl-storage/dg-cephfs-0/public/huangyangke/RapidASR/python/base_wenet/wenet/swig_decoders/_swig_decoders.cpython-37m-x86_64-linux-gnu.so)

### ISSUE THREAD

**Issue by 924726976** [RapidAI/RapidASR#1]
ImportError: /usr/lib64/libm.so.6: version `GLIBC_2.27' not found (required by /mnt/dl-storage/dg-cephfs-0/public/huangyangke/RapidASR/python/base_wenet/wenet/swig_decoders/_swig_decoders.cpython-37m-x86_64-linux-gnu.so)

**Comment by SWHL** [comment]
- 这个问题需要在自己机器上编译安装一下[ctc_decoder](https://github.com/Slyne/ctc_decoder)这个包
- 具体安装步骤可以去[ctc_decoder](https://github.com/Slyne/ctc_decoder)下查看，可以直接参考下面的：
```bash
git clone https://github.com/Slyne/ctc_decoder.git
apt-get update
apt-get install swig
apt-get install python3-dev 
cd ctc_decoder/swig && bash setup.sh
```
