### ISSUE TITLE
请问之前的wenet的项目用的那个模型？

### ISSUE THREAD

**Issue by qiuyuzhao** [RapidAI/RapidASR#10]
之前的git有个关于wenet转onnx的，请问那个项目转的那个模型？自己转的时候encoder维度对不上，您提供的encoder输出是的512的，官方的都是256的

**Comment by SWHL** [comment]
参考[这里](https://github.com/RapidAI/RapidASR/tree/rapid_wenet/python)
昨天刚找回来。。。。

**Comment by qiuyuzhao** [comment]
万分感谢
