### ISSUE TITLE
wenet转onnx的问题

### ISSUE THREAD

**Issue by qiuyuzhao** [RapidAI/RapidASR#11]
请问，我再用wenet转onnx的时候为什么转出来的和您提供的onnx模型结构和输出不一致呢？转的是这个模型。[20211025_conformer_exp](https://wenet-1256283475.cos.ap-shanghai.myqcloud.com/models/aishell/20211025_conformer_exp.tar.gz)

**Comment by SWHL** [comment]
这个我转是用的就是[模型转onnx代码](https://github.com/RapidAI/RapidASR/tree/rapid_wenet/python#%E6%A8%A1%E5%9E%8B%E8%BD%AConnx%E4%BB%A3%E7%A0%81)
转换环境为： `python3.7 torch1.10 1个GPU 16CPU 内存32G`
只能帮到这里了，具体就看不出问题了

**Comment by qiuyuzhao** [comment]
好的，万分感谢
