### ISSUE TITLE
还更新吗？

### ISSUE THREAD

**Issue by LGP-GH** [RapidAI/RapidASR#12]
公告上说 “该项目核心代码已经并入[FunASR](https://github.com/alibaba-damo-academy/FunASR)”，那这个项目是否继续维护？如果继续更新的话，和FunASR会有什么差异？

**Comment by SWHL** [comment]
- 这个项目还会持续更新的。
- 差异在于：我们的项目侧重于工程化落地，更加简洁，不单单拘泥于阿里的ASR

**Comment by LGP-GH** [comment]
好的，谢谢！
