### ISSUE TITLE
报错无法解析模型 。

### ISSUE THREAD

**Issue by standyyyy** [RapidAI/RapidASR#13]
下载百度云的模型，然后用的是venv的环境，按照requirements.txt安装的，但是在运行demo.py的时候报错无法解析。

知道是环境问题，但是不知道是哪个库的版本问题，我昨天在mac上可以跑起来，也没报错，但是今天换到了台式机上发现报错。

`2 0 2 3 - 0 4 - 1 6   1 8 : 3 3 : 2 4 . 2 7 7 1 1 1 0   [ W : o n n x r u n t i m e : D e f a u l t ,   o n n x r u n t i m e _ p y b i n d _ s t a t e . c c : 1 6 4 1   o n n x r u n t i m e : : p y t h o n : : C r e a t e I n f e r e n c e P y b i n d S t a t e M o d u l e ]   I n i t   p r o v i d e r   b r i d g e   f a i l e d . 
 Traceback (most recent call last):
  File "F:/语音识别/RapidASR-2.0.0/demo.py", line 7, in <module>
    paraformer = RapidParaformer()
  File "F:\语音识别\RapidASR-2.0.0\rapid_paraformer\rapid_paraformer.py", line 28, in __init__
    self.ort_infer = OrtInferSession(config['Model'])
  File "F:\语音识别\RapidASR-2.0.0\rapid_paraformer\utils.py", line 304, in __init__
    self.session = InferenceSession(config['model_path'],
  File "F:\语音识别\RapidASR-2.0.0\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 347, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "F:\语音识别\RapidASR-2.0.0\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 384, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from F:\语音识别\RapidASR-2.0.0\rapid_paraformer\models\asr_paraformerv2.onnx failed:Protobuf parsing failed.
`
以上是报错完全信息。
`Package            Version
------------------ ---------
audioread          3.0.0    
certifi            2022.12.7
cffi               1.15.1   
charset-normalizer 3.1.0    
coloredlogs        15.0.1   
decorator          5.1.1    
onnx               1.13.1
onnxruntime        1.13.1
packaging          23.1
pip                21.3.1
platformdirs       3.2.0
pooch              1.7.0
protobuf           3.20.3
pycparser          2.21
pyreadline3        3.4.1
PyYAML             6.0
requests           2.28.2
resampy            0.4.2
scikit-learn       1.2.2
scipy              1.7.3
setuptools         60.2.0
soundfile          0.12.1
sympy              1.11.1
threadpoolctl      3.1.0
typeguard          2.13.3
typing_extensions  4.5.0
urllib3            1.26.15
wheel              0.37.1
zipp               3.15.0
`
因为我上传不了图片，所以以代码块的形式展示目前这个环境的所有库的版本， 期待大佬指点一下。

**Comment by SWHL** [comment]
验证一下你那边下载模型的md5，确定一下是否一致（模型MD5: 9ca331381a470bc4458cc6c0b0b165de）
怀疑是模型下载有问题

**Comment by standyyyy** [comment]
感谢大佬这么会回复，确实是这个问题 ，我重新下载下模型 。
也挺奇怪，这模型是我mac放到阿里云盘然后在下载下来的，下来md5就变了。
还有个问题就是现在长音频不支持吗 ，我尝试放了一首歌进去，识别了一分钟左右，最后出现了一句很短的识别结果，大概5，6个字的那种。

**Comment by standyyyy** [comment]
打错字，是感谢大佬这么快回复

**Comment by SWHL** [comment]
长音频这个，需要后期更新一下了。或者你这边可以贡献一下:smile:

**Comment by SWHL** [comment]
参考这里 [issue15](https://github.com/RapidAI/RapidASR/issues/15)
